config/routes.rb
Rails.application.routes.draw do
  root 'trees#index'
  devise_for :users
  resources :users, only: [:show, :destroy]

  resources :trees, only: [:index, :new, :create, :show]

end

app/models/tree.rb
class Tree < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :description, presence: true,
            length: { minimum: 10 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @trees = Tree.all.order(updated_at: :desc)
  end

  def show
    @tree = Tree.find(params[:id])
  end

  def new
    @tree = Tree.new
  end

  def create
    @tree = current_user.trees.new(tree_params)
    if @tree.save
      redirect_to tree_path(@tree), notice: 'Tree submitted successfully'
    else
      render :new
    end
  end

  private

  def tree_params
    params.require(:tree).permit(:title, :description, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      redirect_to root_url, notice: "Bye! Your account has been successfully
                                    cancelled. We hope to see you again soon."
    end
  end

  def update
    @user = User.find(params[:id])
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XmasTreeReviews</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">XmasTreeReviews</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%= link_to 'Add a Christmas Tree', new_tree_path %>
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'View My Profile', user_path(current_user) %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/trees/_form.html.erb
<div class="errors">
  <% if @tree.errors.any? %>
    <% @tree.errors.full_messages.each do |error| %>
      <%= error %>
      <% end %>
  <% end %>
</div>

<div class="form">
  <%= form_for @tree do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div>
      <%= f.file_field :image %>
    </div>

    <div>
      <%= f.submit 'Submit' %>
    </div>

  <% end %>
</div>

app/views/trees/index.html.erb
<h2> Christmas Trees! </h2>
<ul id="trees">
  <% @trees.each do |tree| %>
    <li><%= link_to tree.title, tree_path(tree) %><br>
    posted by: <%= tree.user.email %> (<%= tree.user.role %>)</li>
  <% end %>
</ul>

app/views/trees/new.html.erb
<h2>Add a Christmas Tree</h2>

<%= render 'form' %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<%= @tree.title %>
<%= @tree.description %>
<% if @tree.image %>
  <%= @tree.image %>
<% end %>
<%= @tree.user.email %>

app/views/users/show.html.erb
<h2> Your Profile </h2>
<%= @user.email %>

<%= link_to 'Edit Account', edit_user_registration_path(@user) %>
<%= link_to 'Delete Account', user_path(@user), method: :delete %>